import { Kanit } from "next/font/google";

import "./globals.css";
const kanit = Kanit({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Loja de Jogos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={kanit.className}>
      <body>{children}</body>
    </html>
  );
}
